### ISSUE TITLE
undefined method `bytesize' for [Rack::Legacy::Cgi, ["/public/"], nil]:Array

### ISSUE THREAD

**Issue by osirisOfGit** [eric1234/rack-legacy#10]
Using Sinatra with your gem, (sorry if that in itself is the problem, fairly new to ruby) and everytime i do use Rack::Legacy::Cgi, 'public' in my post route, my site responds with the error in the title. I don't know why bytesize is getting called when the RACK ENV has its own content length,why this is happening (beyond the type mismatch), or how to solve it.
Appreciate any help.

**Comment by eric1234** [comment]
I've never used it with Sinatra but it should work since it is all rack. Looks like the middleware is not being called correctly. You mentioned doing `use Rack::Legacy::Cgi, 'public'` in your POST route. Do you means you are doing something like:

```
post 'some-route' do
  use Rack::Legacy::Cgi, 'public'
end
```

If so then you are definitely not calling things correctly. The `use` statement should go in your config.ru file.
