### ISSUE TITLE
WordPress and Pow: Connection refused

### ISSUE THREAD

**Issue by jerodsanto** [eric1234/rack-legacy#15]
Hey there. I've been using rack-legacy to serve WordPress from [Pow](http://pow.cx) and it worked great all the way up to `0.3.7`.

(great lib btw, thanks so much for writing it)

After upgrading to `0.9.0` Pow no longer serves my WordPress site and I get the dreaded `Errno::ECONNREFUSED: Connection refused - connect(2)` error staring back at me.

The `config.ru` I use is based off a gist I found floating around the hubs which uses rack-rewrite to make all the WordPress stuff work. Here it is in its entirety:

``` ruby
require "rack"
require "rack-legacy"
require "rack-rewrite"

# patch Php from rack-legacy to substitute the original request so
# WP's redirect_canonical doesn't do an infinite redirect of /
module Rack
  module Legacy
    class Php
      def run(env, path)
        config = {"cgi.force_redirect" => 0}
        config.merge! HtAccess.merge_all(path, public_dir) if @htaccess_enabled
        config = config.collect {|(key, value)| "#{key}=#{value}"}
        config.collect! {|kv| ["-d", kv]}

        script, info = *path_parts(path)
        env["SCRIPT_FILENAME"] = script
        env["SCRIPT_NAME"] = script.sub ::File.expand_path(public_dir), ""
        env["REQUEST_URI"] = env["POW_ORIGINAL_REQUEST"] unless env["POW_ORIGINAL_REQUEST"].nil?

        super env, @php_exe, *config.flatten
      end
    end
  end
end

INDEXES = ["index.html","index.php", "index.cgi"]

use Rack::Rewrite do
  # redirect /foo to /foo/ - emulate the canonical WP .htaccess rewrites
  r301 %r{(^.*/[\w\-_]+$)}, "$1/"

  rewrite %r{(.*/$)}, lambda {|match, rack_env|
    rack_env["POW_ORIGINAL_REQUEST"] = rack_env["PATH_INFO"]

    if !File.exists?(File.join(Dir.getwd, rack_env["PATH_INFO"]))
      return "/index.php"
    end

    to_return = rack_env["PATH_INFO"]
    INDEXES.each do |index|
      if File.exists?(File.join(Dir.getwd, rack_env["PATH_INFO"], index))
        to_return = File.join(rack_env["PATH_INFO"], index)
      end
    end
    to_return
  }
end

use Rack::Legacy::Php, Dir.getwd
use Rack::Legacy::Cgi, Dir.getwd
run Rack::File.new Dir.getwd
```

I see in your commit logs that `0.9.0` is quite a departure from the previous code, so it's quite possible that the `Rack::Legacy::Php` monkey patch isn't working anymore, but I'm hoping you know more about this than I do (I didn't even write the original rackup file, just tweaked it slightly).

I reverted back to `0.3.7` for the time being so no rush on getting a fix on this. Please let me know if there's any other info that would help or anything else I can do.

Thanks!

**Comment by eric1234** [comment]
# Short Answer

Get rid of all that monkey-patching and just use the library as is. The library includes a [rackup file](https://github.com/eric1234/rack-legacy/blob/master/share/rack_legacy.ru) you can use that should be perfectly usable.

# Long Answer

You basically have two monkey-patches.

## Rack::Rewrite

This is being used to function similar to how the [DirectoryIndex](https://httpd.apache.org/docs/2.2/mod/mod_dir.html#directoryindex) command works in Apache. When a directory is requested the index.\* file is executed/served.

Early versions of Rack did not automatically serve index.php when a directory was requested. [A blog article from a few years ago](http://stuff-things.net/2011/05/16/legacy-development-with-pow/) used Rack::Rewrite to work around this. But [about 2 years ago](https://github.com/eric1234/rack-legacy/commit/18a6b97b1cd65d3afb20f54a3cedb0d642d69250) I added direct support for this in rack-legacy for PHP so the Rack::Rewrite hack hasn't been necessary since version 0.3.2.

The recent changes I made [refactored this](https://github.com/eric1234/rack-legacy/commit/0070aed421470a058ea5c861037b9451e87b183e). Rather than having specific support for just PHP I created a rack handler that rewrote the request (similar to Rack::Rewrite but without all the regexp stuff). This allowed me to remove the support in the PHP module and now also support files like index.html and index.cgi. You do need to include this module in your Rack stack (see the [included rackup file](https://github.com/eric1234/rack-legacy/blob/master/share/rack_legacy.ru) for an example usage).

## PHP Hack

I'm not completely sure if I follow your PHP hack but I believe it is trying to work around the same issue as [this commit](https://github.com/eric1234/rack-legacy/commit/317f694e1199169692ea0b0d64d9a3e29970d23b) from a few years ago. Some scripts like Wordpress got in an infinite loop because they make assumptions about the REQUEST_URI environment variable. Your monkey-patch should not be needed after that commit was released (version 0.3.4).

In addition, [recent changes](https://github.com/eric1234/rack-legacy/commit/14ae71bad2dfca52b365c90de042176a238d2340) not only make the monkey-patch unnecessary, but the monkey-patch breaks the app. This is because the most recent release stops using php-cgi to execute the PHP scripts. Instead it now uses  [PHP's built-in webserver](http://us1.php.net/manual/en/features.commandline.webserver.php). Rack-legacy simply proxies the request off to PHP using [rack-reverse-proxy](https://github.com/jaswope/rack-reverse-proxy). Because of this, PHP is handling the request directly. This means removes any possibility for compatability issues like we once had when using the CGI handler and trying to set the environment up right. It also makes requests run MUCH faster as database connections can be cached between requests and we aren't delayed by PHP booting up on each request.

**Comment by jerodsanto** [comment]
Awesome, thanks for the details @eric1234. I'll give it a go with that rackup file you provide and let you know how it goes!

**Comment by jerodsanto** [comment]
@eric1234 stock WordPress 3.8 + rack-legacy 0.9.0 + pow 0.4.1 with the rackup file you linked to results in:

```
Errno::ECONNREFUSED at /index.php
```

The same WordPress 3.8 install + rack-legacy 0.3.7 + pow 0.4.1 works as expected. Any ideas how to troubleshoot this?

**Comment by olliekav** [comment]
I've had to roll back to 0.3.7 as well to get this to work, anyone have any work arounds?

**Comment by eric1234** [comment]
@jerodsanto - I have confirmed that rack-legacy will work with Wordpress. I don't use Mac so I can't test with Pow also in the mix, but I don't see any reason why it should be an issue.

The error you are getting sounds like the PHP web server isn't running. rack-legacy runs the PHP web server as a sub-process and proxies requests off to it. Looks like when Ruby tries to make a connection to the PHP server it's not getting a response. It is run on port 8180 by default (although that can be configured if you have a conflict). See if the PHP server will run for you by itself by changing to your wordpress directory and typing:

```
php -S localhost:8180
```

You should be able to visit your Wordpress site now by opening up your browsers at:

```
http://localhost:8180
```

(Wordpress's canonical redirection bullshit might send you in an infinite loop so you may need to "overwrite the base URL setting":http://codex.wordpress.org/Changing_The_Site_URL#Edit_wp-config.php to http://localhost:8180 to do this test).

Once you've confirmed the PHP server can run, try connecting to it after running the rackup file. Rack-legacy should start up PHP much in the same way you manually did. So you should be able to connect directly to port 8180. Also check your process list to see if the PHP server is running. If you are able to connect to the PHP web server in your browser, Ruby should be able to proxy to it.

NOTE: While testing all of this I did discover a few issues with Wordpress and rack-legacy due to the reverse proxy setup. I have release a new version that solves these problem. Not directly related to your issue but it was preventing Wordpress from working out-of-the-box on rack-legacy.

For now I am keeping this ticket closed as I assume the PHP web server is not running on your computer either because of a port conflict (just change the port) or your PHP version is too old (upgrade to a newer PHP). Feel free to re-open if those assumptions are not correct.

**Comment by ericpeters0n** [comment]
Coming to this years later--

The overall configuration seems to work for the base/root/homepage, but requests to permalinks (Wordpress' bread and butter) don't seem to be correctly interpreted or routed via rack-legacy/POW...

...whereas the site functions perfectly via localhost:8180

**Comment by eric1234** [comment]
I don't use Wordpress but I think last I tested it you had to use "PATHINFO permalinks". I.E.:

```
/index.php/%year%/%monthnum%/%day%/%postname%/
```

This is because there is no mod-rewrite or similar technology in [the default stack](https://github.com/eric1234/rack-legacy/blob/master/share/rack_legacy.ru).

You could use something like rack-rewrite to simulate the same behavior that is in mod-rewrite. Or you could simply subclass the `PHP` handler and override [`valid?`](https://github.com/eric1234/rack-legacy/blob/master/lib/rack/legacy/php.rb#L51) to that it returns true on anything that looks like a permalink (i.e. non-assets).
