### ISSUE TITLE
PHP Breaks Permalinks/Pretty URLs

### ISSUE THREAD

**Issue by eddorre** [eric1234/rack-legacy#18]
I have a Wordpress app that is using permalinks through a plugin, specifically Quick Page/Post Redirect (http://wordpress.org/plugins/quick-pagepost-redirect-plugin/).

A sample url is http://localhost:9292/search-properties

In the call method the first thing that it does is check to see if we have a valid path.

``` ruby
  def valid? path
    return false unless path =~ /\.php/

    path = path[1..-1] if path =~ /^\//
    path = path.split('.php', 2)[0] + '.php'
    path = ::File.expand_path path, @public_dir
    ::File.file? path
  end
```

As you can see valid? returns false immediately if the path doesn't match a regular expression containing .php. This will immediately stop permalinks/pretty URLs. If the permalink does happen to have a .php in it, it will still fail because the actual file doesn't exist.

If I simply return true from the valid? method then everything works as it is supposed to.

If requests are simply being sent to the built in PHP server, can they just go straight there and bypass the file check? PHP will throw a 404 if it can't find the file.

I'd be happy to open a pull request but I wanted to know if I was missing some intent first.

**Comment by eric1234** [comment]
rack-legacy is not setup for a "router file" that is necessary for pretty URLs in PHP. Most PHP apps (I believe Wordpress included) have some sort of non-pretty URL fallback that works. The URL just isn't as clean.

Since rack legacy is middleware we have to have some way of saying PHP is handling this request vs. some other functionality in the rack stack is handling this request. Right now it's focused around the file extension since that is the traditional method that web servers like Apache use.

I'm thinking the ideal pull request should maybe make it configurable through a block. The block should indicate if the PHP middleware should handle the request or not. A default block would provide the current behavior that mimics the standard PHP setup (i.e. files that end in ".php" should be handled by PHP).

But the block could indicate a request without that PHP extension should also be handled by PHP. In this case the block would probably also need to indicate what router file for PHP to use so we can run the PHP webserver with that router file.

Feel free to make a pull requests that implements this behavior.
