### ISSUE TITLE
Multiple Pow Wordpress installs (local), but can only run one at a time

### ISSUE THREAD

**Issue by JCFGD** [eric1234/rack-legacy#20]
I am using the default rackup file;

```
require 'rack/showexceptions'
require 'rack-legacy'

use Rack::ShowExceptions
use Rack::Legacy::Index
use Rack::Legacy::Php
use Rack::Legacy::Cgi
run Rack::File.new Dir.getwd
```

Which is rendering the Wordpress as they should. However, I running into an issue where I can only render one at a time, depending on which one I load first after restarting Pow.

**Example Reproduction**

I have 2 tabs opened, and Pow is running;

wordpressinstall1.dev
wordpressinstall2.dev

Refresh wordpressinstall1, I first receive this error;

```
Errno::ECONNREFUSED at /
Connection refused - connect(2) for "localhost" port 8180

Ruby: /Users/HomeMac/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb: in initialize, line 879
Web: GET wordpressinstall1.dev/
```

After another refresh, the site loads correctly.

Moving over to the wordpressinstall2.dev tap, I refresh that - but when it loads, it display's the content for wordpressinstall1.dev. 

I then restart Pow (using Anvil), and follow the same process, except with wordpressinstall2.dev.

Refresh tab, receive error, refresh again, site loads, use the wordpressinstall1.dev url, receive wordpressinstall2.dev's content.

If I want one or the other, I have to refresh Pow and load the site I want to render.

_A thing to note that if I am logged into the admin in wordpressinstall1.dev but use the wordpress2.dev URL, I am not logged in - I am only logged in on the first URL_

**Comment by eric1234** [comment]
This is likely due to the fact that [about half a year ago](https://github.com/eric1234/rack-legacy/commit/14ae71bad2dfca52b365c90de042176a238d2340) I switched from using PHP's CGI interface to instead proxy the PHP requests off to PHP's internal server.

This was done for performance. Starting a fresh process with every request meant information cannot persist between requests. Specifically this affected database interaction heavily as new connections had to be established for every request.

The new setup runs the PHP webserver on [port 8180 by default](https://github.com/eric1234/rack-legacy/blob/master/lib/rack/legacy/php.rb#L23). If you are trying to run two separate instances of Rack::Legacy::Php this means it will start up two different php processes. But if you are using the default port they will both try attaching to port 8180. The first will succeed. The second will not.

The solution is to simply specify the port for PHP to run on when using Rack::Legacy::Php.

A quick search shows [it might be possible](http://stackoverflow.com/a/201528/120067) to let Ruby pick a random unused port. Feel free to test this out and submit a patch if you have the time. Or just specify the port until I get an opportunity to investigate myself.

**Comment by JCFGD** [comment]
Thanks for getting back to me on this. Thanks to your comments and references, I was able to put together a solution in one line in **php.rb**;

Before:

```
def initialize app, public_dir=Dir.getwd, php_exe='php', port=8180, quiet=false
```

After:

```
def initialize app, public_dir=Dir.getwd, server=TCPServer.new('127.0.0.1', 0), php_exe='php', port=server.addr[1], quiet=false
```

**Comment by eric1234** [comment]
Good to know that TCPServer can be used to find a free port. 

I think if I was going to make the change I would not want to add "server" as an argument to initialize. In fact I think it would be best to actually remove "port" as an argument. Having "port" as an argument was really just a workaround in case that port I picked was in use. If we have a way to always get an un-used port there is no need to allow the user to specify the port of the PHP server. So I'll probably just move the TCPServer stuff to be internal to Rack::Legacy::Php.

If you can submit a patch great. Otherwise I'll probably get some free time in the next few days to knock it out.

**Comment by JCFGD** [comment]
Agreed on not adding server and getting rid of port. I did it the way I did it based on <a href="http://stackoverflow.com/questions/200484/how-do-you-find-a-free-tcp-server-port-using-ruby/201528#201528">that Stack Overflow</a> question/answer you had referenced.

If I have time I'll see if I can get a patch working using the method you've suggested, but for the meantime I'll just ride it out with the quick fix I implemented.

**Comment by eric1234** [comment]
BTW, I eventually followed up on this (only took me 2 months :) ).

Just made [a commit](https://github.com/eric1234/rack-legacy/commit/391e7fc2899a487cd89b6a765cb6225e277cc326) that will allow rack-legacy to dynamically select the port so the user no longer needs to specify the port if they are running multiple instances of rack-legacy or are conflicting in some other way.
